import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import tw from "tailwind-styled-components";

const PageContainer = tw.div`
flex min-h-screen flex-col items-center px-16
`;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <PageContainer>{children}</PageContainer>

        <Footer />
      </body>
    </html>
  );
}
